spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    top.chengdonglu.mall210.wx:  DEBUG
    top.cehngdonglu.mall210:  ERROR

swagger:
  production: false
