# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Deploy to Aliyun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build the Package with Maven
      run: |
          mvn install
          mvn clean package
    - name: Deploy the package to the remote server
      uses: appleboy/scp-action@v0.0.1
#     - name: Run a script on remote server (start the application)
#       if: always()
#       uses: fifsky/ssh-action@master
#       with:
#         command: |
#           cd hacene/demo/actions/ && java -Dfile.encoding=UTF-8 -jar litemall-all/target/litemall-all-0.1.0-exec.jar &
#         host: ${{ secrets.HOST }}
#         user: ${{ secrets.SSH_USER }}
#         pass: ${{ secrets.SSH_PASSWORD }}
          
