# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Deploy to Aliyun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SSH to my server and deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST_IP }}
          passphrase: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} 
          script: |
            cd /home/mall210/backend/chengdonglu210-backend/
            git pull
            mvn install
            mvn clean package
            java -Dfile.encoding=UTF-8 -jar litemall-all/target/litemall-all-0.1.0-exec.jar
          script_stop: echo "stop script after first failure"
